In [1]:
import numpy as np

In [2]:
mylist= [1,2,3]

In [3]:
type(mylist)

list

In [5]:
myarr=np.array(mylist)

In [7]:
type(myarr)

numpy.ndarray

In [12]:
np.arange(0,100,20)

array([ 0, 20, 40, 60, 80])

In [17]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [19]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.random.rand(2,5)

array([[0.98109594, 0.68176597, 0.79372583, 0.56634142, 0.61399758],
       [0.96472469, 0.59276294, 0.85130428, 0.93403438, 0.40702182]])

In [30]:
np.random.randn(10)

array([ 0.73999145, -0.81335457,  0.94156788, -1.16668939,  0.8359549 ,
       -0.21433357, -0.69398377,  0.53250299, -0.48904826, -0.94636953])

In [33]:
np.random.randint(0,101,10)

array([52, 25, 99,  4, 44, 29,  0, 87, 17, 16])

In [46]:
np.random.seed(2)
np.random.rand(4)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239])

In [47]:
np.random.seed(2)
np.random.rand(4)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239])

In [49]:
ranarr=np.random.randint(0,101,10)

In [51]:
ranarr

array([34, 49, 95, 75, 85, 47, 63, 31, 90, 20])

In [52]:
ranarr.max()

95

In [53]:
ranarr.min()

20

In [54]:
ranarr.argmax()

2

In [55]:
ranarr.argmin()

9

In [57]:
ranarr.dtype


dtype('int64')

In [60]:
myarray=np.linspace(0,10,101,endpoint=True)
print(myarray)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10. ]


In [61]:
arr=np.arange(0,11)

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr[8]

8

In [67]:
arr[0:4]

array([0, 1, 2, 3])

In [68]:
arr[:5]

array([0, 1, 2, 3, 4])

In [69]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

arr[0:5]=100

In [71]:
arr[0:5]=100

In [72]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [73]:
arr=np.arange(0,11)

In [75]:
slice_of_arr=arr[0:5]

In [76]:
slice_of_arr


array([0, 1, 2, 3, 4])

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
slice_of_arr[:]=99

In [79]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [80]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [81]:
arr=np.arange(0,10)

In [82]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [84]:
arr -2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [85]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [86]:
arr.mean()

4.5

In [91]:
arr2d=np.arange(0,25).reshape(5,5)

In [92]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [100]:
arr2d.shape

(5, 5)

this arr adds the value in a horizantal way if axis is 1 and vertically if axis is 0

In [101]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])